<a href="https://colab.research.google.com/github/hikhm/Tensorflow2-study/blob/main/01%EC%9E%A5_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_2_0%EC%9C%BC%EB%A1%9C_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EA%B5%AC%ED%98%84_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

EPOCHS = 200
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10 
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2

mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

print(len(X_train))
print(len(X_test))
print(tf.shape(X_train))
print(tf.shape(X_test))
RESHAPED = 784 #28*28

X_train = X_train.reshape(60000,RESHAPED)
X_test = X_test.reshape(10000,RESHAPED)
print(tf.shape(X_train))
print(tf.shape(X_test))

X_train = X_train.astype('float32') # 가중치 등에서 float 형태의 값들이 산출되기떄문에 int보다 float가 일반적인 형태
X_test = X_test.astype('float32')

#입력을 [0,1]사이로 정규화
X_train /= 255
X_test /=255
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

Y_train = tf.keras.utils.to_categorical(Y_train, NB_CLASSES)
Y_test = tf.keras.utils.to_categorical(Y_test, NB_CLASSES)

model = tf.keras.models.Sequential()
#model.add(keras.layers.Dense(NB_CLASSES,
#                             input_shape=(RESHAPED,), 
#                             kernel_initializer='zeros', #가중치 0으로 초기화, random_uniform:-0.05~0.05사이 균등분포, random_normal : 평균0, 표준편차 0.05로 초기화
#                             name = 'dense_layer',
#                             activation='softmax'))
DROPOUT=0.3
model.add(keras.layers.Dense(N_HIDDEN,
                             input_shape = (RESHAPED,),
                             name='dense_layer', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(N_HIDDEN,
                             name='dense_layer_2', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))
model.add(keras.layers.Dense(NB_CLASSES,
                             name='dense_layer_3', activation='softmax'))

model.compile(optimizer='SGD',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(X_train, Y_train,
          batch_size = BATCH_SIZE, epochs=EPOCHS,
          verbose = VERBOSE, validation_split = VALIDATION_SPLIT)

60000
10000
tf.Tensor([60000    28    28], shape=(3,), dtype=int32)
tf.Tensor([10000    28    28], shape=(3,), dtype=int32)
tf.Tensor([60000   784], shape=(2,), dtype=int32)
tf.Tensor([10000   784], shape=(2,), dtype=int32)
60000 train samples
10000 test samples
Epoch 1/200
375/375 [==============================] - 2s 5ms/step - loss: 2.0137 - accuracy: 0.3112 - val_loss: 0.8872 - val_accuracy: 0.8131
Epoch 2/200
375/375 [==============================] - 2s 4ms/step - loss: 1.0029 - accuracy: 0.6959 - val_loss: 0.5272 - val_accuracy: 0.8687
Epoch 3/200
375/375 [==============================] - 2s 4ms/step - loss: 0.7216 - accuracy: 0.7770 - val_loss: 0.4227 - val_accuracy: 0.8881
Epoch 4/200
375/375 [==============================] - 2s 4ms/step - loss: 0.6130 - accuracy: 0.8141 - val_loss: 0.3734 - val_accuracy: 0.8970
Epoch 5/200
375/375 [==============================] - 2s 4ms/step - loss: 0.5424 - accuracy: 0.8357 - val_loss: 0.3427 - val_accuracy: 0.9041
Epoch 6/200
375/375 [=

In [ ]:
test_loss, test_acc = model.evaluate(X_test, Y_test, batch_size=BATCH_SIZE)
print('Test accuracy : ', test_acc)

79/79 [==============================] - 0s 2ms/step - loss: 0.0767 - accuracy: 0.9772
Test accuracy :  0.9771999716758728


In [46]:
!git clone https://github.com/hikhm/test.git

Cloning into 'test'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
